# coding: utf-8

"""
    Visier Document Search API

    Visier API for searching for Visier documents

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_model_query_python_sdk
from visier_model_query_python_sdk.model.document_search_link_dto import DocumentSearchLinkDTO
from visier_model_query_python_sdk import configuration


class TestDocumentSearchLinkDTO(unittest.TestCase):
    """DocumentSearchLinkDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
