# coding: utf-8

"""
    Visier Document Search API

    Visier API for searching for Visier documents

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_model_query_python_sdk
from visier_model_query_python_sdk.model.status import Status
from visier_model_query_python_sdk import configuration


class TestStatus(unittest.TestCase):
    """Status unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
