# coding: utf-8

"""
    Visier Document Search API

    Visier API for searching for Visier documents

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_model_query_python_sdk.paths.v1alpha_search_simple_document_headers.get import SimpleSearchDocumentHeadersRaw


class DocumentSearchApiRaw(
    SimpleSearchDocumentHeadersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
