# coding: utf-8

"""
    Visier Document Search API

    Visier API for searching for Visier documents

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDocumentSearchLinkDTO(TypedDict):
    pass

class OptionalDocumentSearchLinkDTO(TypedDict, total=False):
    # The URL pointing to the specific document.
    href: str

    # The verb to use when formulating the web request. This is commonly `GET`.
    verb: str

class DocumentSearchLinkDTO(RequiredDocumentSearchLinkDTO, OptionalDocumentSearchLinkDTO):
    pass
